name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Unit tests
        run: go version && go test -timeout 30s github.com/frezbo/repos
        env:
          PERSONAL_ACCESS_TOKEN: "dummy-token"
      - uses: pulumi/actions@v1.2.0
        with:
          command: preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          INFRA_DNS_CLOUDFLARE_API_TOKEN: ${{ secrets.INFRA_DNS_CLOUDFLARE_API_TOKEN }}
          INFRA_DO_DIGITALOCEAN_TOKEN: ${{ secrets.INFRA_DO_DIGITALOCEAN_TOKEN }}
          DOCKER_ACTIONS_TEST_GHCR_ACCESS_TOKEN: ${{ secrets.DOCKER_ACTIONS_TEST_GHCR_ACCESS_TOKEN }}
          DOCKERFILES_GHCR_ACCESS_TOKEN: ${{ secrets.DOCKERFILES_GHCR_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_PR_WORKFLOW: true
          COMMENT_ON_PR: 1
