name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Unit tests
        run: go test -timeout 30s github.com/frezbo/repos
        env:
          PERSONAL_ACCESS_TOKEN: "dummy-token"
      - uses: pulumi/action-install-pulumi-cli@v1
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: prod
          comment-on-pr: true
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          INFRA_DNS_CLOUDFLARE_API_TOKEN: ${{ secrets.INFRA_DNS_CLOUDFLARE_API_TOKEN }}
          INFRA_DO_DIGITALOCEAN_TOKEN: ${{ secrets.INFRA_DO_DIGITALOCEAN_TOKEN }}
          DOCKER_ACTIONS_TEST_GHCR_ACCESS_TOKEN: ${{ secrets.DOCKER_ACTIONS_TEST_GHCR_ACCESS_TOKEN }}
          DOCKERFILES_GHCR_ACCESS_TOKEN: ${{ secrets.DOCKERFILES_GHCR_ACCESS_TOKEN }}
