name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          stable: true
          go-version: '1.17.2'
      - uses: pulumi/action-install-pulumi-cli@v2
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          INFRA_DNS_CLOUDFLARE_API_TOKEN: ${{ secrets.INFRA_DNS_CLOUDFLARE_API_TOKEN }}
          INFRA_DO_DIGITALOCEAN_TOKEN: ${{ secrets.INFRA_DO_DIGITALOCEAN_TOKEN }}
          DOCKER_ACTIONS_TEST_GHCR_ACCESS_TOKEN: ${{ secrets.DOCKER_ACTIONS_TEST_GHCR_ACCESS_TOKEN }}
          DOCKERFILES_GHCR_ACCESS_TOKEN: ${{ secrets.DOCKERFILES_GHCR_ACCESS_TOKEN }}
